// Validators for decision-scenario deliberation state.
//
// Deliberately import-light (only ./ids) so the engine, the world serializer and
// React can all use it. world.ts and agent.ts import each other, so a validator
// needed by both cannot live in either — same reason affinity.ts and
// relationshipEvents.ts are their own leaf modules.

import { Infer, v } from 'convex/values';
import { playerId } from './ids';

// A candidate the group is choosing between, generated by the Decider at the
// start of a decision scenario (see convex/decider.ts).
export const serializedDecisionOption = v.object({
  optionId: v.string(),
  title: v.string(),
  details: v.string(),
});
export type SerializedDecisionOption = Infer<typeof serializedDecisionOption>;

// The focal agent's belief about one option. Everything here is an ESTIMATE under
// incomplete information — the true scores are computed separately, afterwards,
// by convex/evaluator.ts against ground truth nobody in the conversation can see.
export const serializedOptionEstimate = v.object({
  optionId: v.string(),
  estimatedScore: v.number(),
  tabooRisk: v.boolean(),
  // Participants the focal agent suspects of an undisclosed hard constraint
  // against this option. Non-empty means some estimated U_i could be 0.
  riskyForPlayerIds: v.optional(v.array(playerId)),
});

// Live state of a decision scenario's deliberation.
export const serializedDeliberation = v.object({
  // The participant who runs the deliberation: asks the clarifying questions and
  // makes the final call. Chosen deterministically (lowest-sorting participant
  // id) so every agent independently agrees on who it is.
  focalPlayerId: playerId,
  options: v.array(serializedDecisionOption),
  // Set once the option-generation op has been requested, so it fires exactly
  // once. Mirrors `taskPlanRequested`.
  optionsRequested: v.optional(v.boolean()),
  estimates: v.optional(v.array(serializedOptionEstimate)),
  // The leading option and its estimated group utility at each completed focal
  // turn. The stability criterion compares against the last entry; storing the
  // option id too means a changed front-runner reads as unstable, which it is.
  topScoreHistory: v.optional(
    v.array(v.object({ optionId: v.string(), groupUtility: v.number() })),
  ),
  // Which stopping criteria are still unmet ('taboo' | 'margin' | 'stability' |
  // 'insufficient-options'), for the deliberation panel's "waiting on" line.
  blockedBy: v.optional(v.array(v.string())),
  questionsAsked: v.optional(v.number()),
  resolvedOptionId: v.optional(v.string()),
  resolvedAt: v.optional(v.number()),
  // True when a safety valve (question budget, message cap, scenario expiry)
  // forced the commitment instead of the criteria being satisfied.
  forcedDecision: v.optional(v.boolean()),
  // Set once the evaluation op has been scheduled, so it fires exactly once.
  evaluationRequested: v.optional(v.boolean()),
  // --- Live cues for the map (see src/components/Character.tsx) ---
  // Who the focal agent last put a question to, and when. Drives the pulsing "?"
  // over that resident's head while they are on the spot.
  lastQuestion: v.optional(v.object({ targetPlayerId: playerId, at: v.number() })),
  // How many genuinely new facts the Decider pulled out of the transcript on the
  // last focal turn, and when — drives the "💡 +N" floater over the focal agent.
  lastExtraction: v.optional(v.object({ count: v.number(), at: v.number() })),
});
export type SerializedDeliberation = Infer<typeof serializedDeliberation>;

// What one completed focal turn changes about the deliberation. Produced by
// convex/focal.ts and carried back through agentSendMessage ->
// agentFinishSendingMessage, the same route goalMet and coveredTopics take.
export const focalTurnDelta = v.object({
  estimates: v.array(serializedOptionEstimate),
  topScore: v.optional(v.object({ optionId: v.string(), groupUtility: v.number() })),
  blockedBy: v.array(v.string()),
  askedQuestion: v.boolean(),
  // Who the question was put to, when one was asked.
  questionTargetId: v.optional(playerId),
  // Net-new facts the Decider extracted from the transcript this turn.
  factsLearned: v.optional(v.number()),
  resolvedOptionId: v.optional(v.string()),
  forcedDecision: v.optional(v.boolean()),
});
export type FocalTurnDelta = Infer<typeof focalTurnDelta>;

// Apply a completed focal turn to the deliberation. Shared by the input handler
// so the engine's write and the dry run's write can't drift apart.
export function applyFocalTurn(
  deliberation: SerializedDeliberation,
  delta: FocalTurnDelta,
  now: number,
): void {
  deliberation.estimates = delta.estimates;
  deliberation.blockedBy = delta.blockedBy;
  if (delta.topScore) {
    deliberation.topScoreHistory = [...(deliberation.topScoreHistory ?? []), delta.topScore].slice(
      -8,
    );
  }
  if (delta.askedQuestion) {
    deliberation.questionsAsked = (deliberation.questionsAsked ?? 0) + 1;
    if (delta.questionTargetId) {
      deliberation.lastQuestion = { targetPlayerId: delta.questionTargetId, at: now };
    }
  }
  if (delta.factsLearned && delta.factsLearned > 0) {
    deliberation.lastExtraction = { count: delta.factsLearned, at: now };
  }
  if (delta.resolvedOptionId && !deliberation.resolvedOptionId) {
    deliberation.resolvedOptionId = delta.resolvedOptionId;
    deliberation.resolvedAt = now;
    deliberation.forcedDecision = !!delta.forcedDecision;
  }
}
